task: 'deform'
gpus: [0]

parent_cfg: 'configs/aninerf_s9p.yaml'

train_dataset:
    data_root: 'data/zju_mocap/CoreView_377'
    human: 'CoreView_377'
    ann_file: 'data/zju_mocap/CoreView_377/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/zju_mocap/CoreView_377'
    human: 'CoreView_377'
    ann_file: 'data/zju_mocap/CoreView_377/annots.npy'
    split: 'test'

test:
    sampler: 'FrameSampler'
    frame_sampler_interval: 30

# data options
H: 1024
W: 1024
ratio: 0.5
training_view: [0, 6, 12, 18]
init_aninerf: 'no_pretrain'
num_train_frame: 300
num_eval_frame: 200
begin_ith_frame: 0
frame_interval: 1
smpl: 'new_smpl'
vertices: 'new_vertices'
params: 'new_params'
big_box: True
